<a href="https://colab.research.google.com/github/siddharth10-dev/data-viz-python/blob/main/DATA_DAY2ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
print(a)

[1 2 3 4 5]

In [ ]:
a[::2]

array([1, 3, 5])

In [ ]:
a[:2]

array([1, 2])

In [ ]:
b = np.arange(5)

In [ ]:
print(b)

[0 1 2 3 4]

In [ ]:
np.random.random(size=2)

array([0.03555814, 0.02655026])

In [ ]:
np.random.rand(2,4)

array([[0.95541435, 0.66214217, 0.31377639, 0.72646115],
       [0.44511937, 0.358785  , 0.46692555, 0.4874303 ]])

Arange

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

Reshape

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [ ]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.empty((3,3))

array([[2.27991096e-315, 0.00000000e+000, 2.28538175e-315],
       [6.55338476e-310, 2.28188139e-315, 5.72938865e-313],
       [0.00000000e+000, 6.55314740e-310, 3.95252517e-322]])

In [ ]:
np.empty(5)

array([2.14363891e-315, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       2.37151510e-322])

# Pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
g7_pop = [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.52]
pd.Series(g7_pop , index = ["Canada","France","Germany","Italy","Japan","United Kingdom","United States"])

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.520
dtype: float64

In [ ]:
g7_pop

[35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.52]

In [ ]:
g7_pop_series = pd.Series(g7_pop , index = ["Canada","France","Germany","Italy","Japan","United Kingdom","United States"])
print(g7_pop_series[0])

35.467

/tmp/ipython-input-2567492070.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(g7_pop_series[0])

In [ ]:
g7_pop_series.mean()

np.float64(107.30214285714285)

In [ ]:
g7_pop

[35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.52]

In [ ]:
import kagglehub
path = kagglehub.dataset_download("neuromusic/avocado-prices")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/neuromusic/avocado-prices?dataset_version_number=1...

100%|██████████| 629k/629k [00:00<00:00, 84.8MB/s]

Extracting files...

In [ ]:
import os
csv_file_path = os.path.join(path, 'avocado.csv')
df = pd.read_csv(csv_file_path)
df.head()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [ ]:
import kagglehub
path = kagglehub.dataset_download("die9origephit/fifa-world-cup-2022-complete-dataset")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/die9origephit/fifa-world-cup-2022-complete-dataset?dataset_version_number=7...

100%|██████████| 7.42k/7.42k [00:00<00:00, 13.4MB/s]

Extracting files...

In [ ]:
import os
csv_file_path = os.path.join(path, 'Fifa_world_cup_matches.csv')
df = pd.read_csv(csv_file_path)
df.head()

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361

In [ ]:
team1=pd.DataFrame(df["team1"])
team1.head()

           team1
0          QATAR
1        ENGLAND
2        SENEGAL
3  UNITED STATES
4      ARGENTINA

In [ ]:
df.date

0     20 NOV 2022
1     21 NOV 2022
2     21 NOV 2022
3     21 NOV 2022
4     22 NOV 2022
         ...
59    10 DEC 2022
60    13 DEC 2022
61    14 DEC 2022
62    17 DEC 2022
63    18 DEC 2022
Name: date, Length: 64, dtype: object

In [ ]:
dates=pd.DataFrame(df["date"])
dates.head()

          date
0  20 NOV 2022
1  21 NOV 2022
2  21 NOV 2022
3  21 NOV 2022
4  22 NOV 2022